### ISSUE TITLE
Search,Pagination, Redirction > Duplicate Content

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1341]
We get a duplicate content penalty on those core parts : 
- Search => same SEO Title and SEO Description
  - /search/?q=queyras vs /search vs /search/news/
  - i would also add in the page a meta robots tag with "noindex, follow" in this query result page
- Pagination => same SEO Title and SEO Description
  - /news vs /news?page=3 
  -  here the solution is to add, in Page SEO Title, an extra  "| Page `<nr>`" from page above 1 in paginator
  - the same for description, add the this at the start of the description value
  - we need also the rel=”next” and rel=”prev” tags (see http://googlewebmastercentral.blogspot.in/2011/09/pagination-with-relnext-and-relprev.html) - only `next` for first page / only `prev` for latest page
  - more globally follow https://developers.google.com/structured-data/breadcrumbs
- Redirection on login & registration => same SEO Title and SEO Description
  - /user/register/?redirect=/contact vs user/register/?redirect=/contact
  - /user/login/?redirect=/contact /user/login/?redirect=/search
  - can we imagine to pass the redirection differently, i.e. with no query parameter (that are also not advised)? => the redirection generates a lot of URLS with same content (the login page), so it polutes the real urls for the site (those with real content) , overwhelming the real content with "technical" false page with redirection => we get a SEO penalty here

**Comment by Marc-pi** [comment]
those issue are very critical to fix.
now since we fixed the Hn issue, Google and Bing are reporting us the other weaknesses that were hidden behind the hiearchy issue => we need to fix those asap

**Comment by Marc-pi** [comment]
@voltan @taiwen 
for redirect (and any login/register button), seems bootstrap modal box is the right solution

**Comment by voltan** [comment]
this http://getbootstrap.com/javascript/#modals ?
open result on pupup ? for login/register not bad , but I still don't understand problem, can we fix it buy set any meta header ?

**Comment by Marc-pi** [comment]
> for login/register not bad , but I still don't understand problem

for register, we can keep the actual page, it is ok, its unicity is real
but we have an issue on login page for restricted areas/forms :
* on user side : being redirected if very bad, bad UX, user don't like to be bounced from another page to come back to the initial page, bad experience => make it easier
* on crawler side : it takes crawl quota, and virtual pages are created for each redirect => duplicate content pages since they are all similar

Solutions : 
* display login fields directly on the page (takes place) => modal is made for this
* transmit redirection with another way than url based
* Many leading websites are using modals to fix that nowadays (ex:  AirBnB), redirect is the old way 
i guess after fill in the fields, the page is reloading with the session ID and ads a cookie
the solution : the login box does not exist since it is directly a form embedded within a page. 
since many are doing this, i think it is a secure method : just one page is embedded in this modal.

> can we fix it buy set any meta header ?

no, on redirect we create a new virtual page => DC

**Comment by Marc-pi** [comment]
for search, we need to add a hash (#) in the url
crawlers do not take into account whatever is after the hash. 
see how google works itself https://www.google.fr/#q=queyras
@voltan this will solve other of our issues with filters param withins url :-)

**Comment by Marc-pi** [comment]
search and paginator were fixed
Next : Pi redirection

> Redirection on login & registration => same SEO Title and SEO Description
* /user/register/?redirect=/contact vs user/register/?redirect=/contact
 * /user/login/?redirect=/contact /user/login/?redirect=/search
> Can we imagine to pass the redirection differently, i.e. with no query parameter (that are also not advised)? => the redirection generates a lot of URLS with same content (the login page), so it polutes the real urls for the site (those with real content) , overwhelming the real content with "technical" false page with redirection => we get a SEO penalty here


we have to replace it by a server side redirect, instead of get method. This can be done by using modals and/or cookies.

**Comment by Marc-pi** [comment]
not finished, see yesterday comment
